# Generated by Django 3.0.7 on 2020-07-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesion', models.CharField(max_length=400)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='canteen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesion', models.CharField(max_length=400)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Query_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesion', models.CharField(max_length=400)),
                ('answer', models.TextField()),
                ('is_admission', models.BooleanField(default=False, verbose_name='is_admission')),
                ('is_canteen', models.BooleanField(default=False, verbose_name='is_canteen')),
                ('is_faculty', models.BooleanField(default=False, verbose_name='is_faculty')),
                ('is_infra', models.BooleanField(default=False, verbose_name='is_infra')),
                ('satisfied', models.IntegerField(default=0, verbose_name='satisfied')),
                ('unsatisfied', models.IntegerField(default=0, verbose_name='unsat')),
                ('viewed', models.IntegerField(default=0, verbose_name='viewed')),
            ],
        ),
    ]
